FROM ruby:3.2.2-alpine

RUN apk add --no-cache build-base postgresql-dev tzdata

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle config set --local without 'development test' \
 && bundle install

COPY . .

RUN mkdir -p tmp/pids log

EXPOSE 3000

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
